### ISSUE TITLE
compilation error 

### ISSUE THREAD

**Issue by cineguerrilha** [dfgordon/a2kit#1]
Hi, I am getting several errors like 

error[E0308]: mismatched types
   --> /home/leao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/a2kit-2.7.0/src/lang/merlin/tokenizer.rs:150:23
    |
150 |         parser.set_language(tree_sitter_merlin6502::language()).expect("error loading merlin grammar");
    |                ------------ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `tree_sitter::Language`, found a different `tree_sitter::Language`
    |                |
    |                arguments to this method are incorrect

if i use cargo install a2kit (v2.7.0)but it compiles fine if I compile it from the git repository (v3). However, the package I am trying to install bas2wav calls v2 and cargo.toml pointing to v3 does not work as it does not find it. I am new to rust and have no idea how to proceed and your help will be greatly appreciated!

**Comment by dfgordon** [comment]
Thanks for pointing this out. It appears the semantic versioning rules were violated as a result of parser updates, probably breaking a few v2 variants. Indeed v3 is not yet released and at any rate being a major update would not be recommended for something relying on v2. So the workaround I think is to checkout the version you need and edit cargo.toml to use the exact version of all the tree sitter crates. See SemVer compatibility in the cargo book. Basically you add a tilde or better yet an equals sign.Once you have that do cargo install locally.I will try to figure a better solution soon.Sent from my iPhoneOn Jul 24, 2024, at 11:35 PM, cineguerrilha ***@***.***> wrote:﻿
Hi, I am getting several errors like
error[E0308]: mismatched types
--> /home/leao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/a2kit-2.7.0/src/lang/merlin/tokenizer.rs:150:23
|
150 |         parser.set_language(tree_sitter_merlin6502::language()).expect("error loading merlin grammar");
|                ------------ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected tree_sitter::Language, found a different tree_sitter::Language
|                |
|                arguments to this method are incorrect
if i use cargo install a2kit (v2.7.0)but it compiles fine if I compile it from the git repository (v3). However, the package I am trying to install bas2wav calls v2 and cargo.toml pointing to v3 does not work as it does not find it. I am new to rust and have no idea how to proceed and your help will be greatly appreciated!

**Comment by dfgordon** [comment]
There is an easier workaround, just use the `--locked` flag.

`cargo install bas2wav --locked`

People who just want a2kit can similarly run

`cargo install a2kit --locked`

Evidently the trouble started with tree-sitter-merlin6502 v2.2.0 which induces tree-sitter v0.22.x which uses a different language format.  It seems the only general solution is to yank this in favor of a patch update that rolls back the tree-sitter version.  May take a couple days.

**Comment by dfgordon** [comment]
The offending crates have been yanked, `cargo install bas2wav` and `cargo install a2kit` should now work.
